### ISSUE TITLE
Should the extension warn that rls.toml is deprecated?

### ISSUE THREAD

**Issue by booyaa** [rust-lang-nursery/rls-vscode#107]
It might be superseded in vscode, but what about for other editors?

I've added the screenshot for reference:

![screen shot 2017-08-05 at 13 14 08](https://user-images.githubusercontent.com/192864/28995394-0bd2e1f2-79e0-11e7-8c46-fb1d04f5a32a.png)

update 1: noticed that `.rls.toml` doesn't cause any warnings. Should we update the rls [documentation](https://github.com/rust-lang-nursery/rls#configuration) to remove `rls.toml`?

**Comment by nrc** [comment]
The warning should trigger for .rls.toml too.

The rls.toml is ignored by the RLS (i.e., by all editors). Other editors should also warn, but they don't have to and there is nothing the RLS can do about it.

**Comment by booyaa** [comment]
Slight deviation, but if the toml is deprecated how are defaults overridden by other editors other than vscode?

**Comment by Xanewok** [comment]
@booyaa LSP clients should send a `workspace/didChanceConfiguration` [request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspace_didChangeConfiguration) passing, if I'm not mistaken, this to `settings`:
```javascript
{
    "rust": { // Options under "rust" key are passed as a config now, e.g.:
        "build_lib": true
        // ...
   }
}
```
I'm also using neovim alongside vscode, so I'll get back after I'll figure out how to pass custom options to the RLS via the neovim LSP client.

**Comment by nrc** [comment]
Yeah, passing configuration is a standard part of the LSP, so any client can do it. Exactly how the client exposes config options to the user is up to the client.

**Comment by booyaa** [comment]
closing this now that the documentation has been updated

**Comment by mickaelistria** [comment]
> LSP clients should send a workspace/didChanceConfiguration request passing

So this require every clients to develop a specific integration, while relying on a file allowed customization without specific development, and even allowed users to deal with the configuration by themselves.
The approach of relying on client to customize stuff is inferior technically and in term of UX in several cases to the approach of editing a file. Trust me, I'm working on Eclipse IDE, and we got a lot of requests like "I just want .editorconfig", "I just want to edit the pom file"...). End-users like to deal with configuration files over tool-specific stuff, it makes the project more portable to other tools and users.
I suggest you revive support for .rls.toml files in order to make RLS usable beyond VSCode-specific integration.
