### ISSUE TITLE
Add command to restart the RLS

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rls-vscode#129]
I can't find docs on how to do this exactly, but I expect one sends the `shutdown` and `exit` messages, then calls `stop`, then `start` on the language client. (But perhaps `stop` sends the LSP messages?).

**Comment by genneth** [comment]
Had a quick go --- notes so far:
* `stop` definitely stops the server. 
* However, it seems that you can't just call `start` again on the same `LanguageClient` object. Looking at the source for `LanguageClient`, it does look like the server is started in or via the constructor, so we would need to create a whole new instance. Not super sure where is the best place to stash said instance though. Initially thought somewhere inside the `ExtensionContext` might be best, but pretty sure that's just because I haven't understood how VS code extensions are supposed to work...

**Comment by nrc** [comment]
Yeah, it is probably best that we create a new RLS so that it does not carry over any bad state. I don't think you should need to stash the instance anywhere. I think you create a new and then `push` the disposable returned by `start` on to `context.subscriptions` to ensure it gets disposed.

One thing to check is that on restart, the client sends changes for any open and changed files.

**Comment by genneth** [comment]
I think it's necessary because the registered commands all refer to a captured `lc` in their closures. I think creating a new one will launch, but then the commands won't work... Will test it though
