### ISSUE TITLE
Publish as vscode extension to Marketplace

### ISSUE THREAD

**Issue by perlun** [rust-lang-nursery/rls-vscode#13]
First, thanks for an _amazing_ thing! The initial impression is really great: even I know is this is way pre-alpha and all of that, it's still an awesome feeling to launch this. It gives you something like the TypeScript editing experience in VSCode, which is really really nice. So, thanks a lot for what has already been done.

Having that said: have we considered publishing this as a "real" vscode extension, i.e. something you can just download and run? The current setup experience is "a bit" 😉 rough on the edges, of course I understand like everyone else why this is the case (we've mostly focused on getting the dev environment up thus far), but do you @jonathandturner see any immediate obstacles to publishing this to the VSCode Marketplace? Do you think it would be premature to do that at this stage? We can give an extremely low version number like 0.0.1 to make sure people understand what to expect...

(We will still depend on the `rls` binary being available, downloaded and compiled by the user, but we can't really do much about that yet, and that's pretty much fine.)

**Comment by nrc** [comment]
Yes, the plan is to make a vs code that can be downloaded and installed via the marketplace. However, that is a little way off yet (we haven't issued an alpha yet, and this should wait for at least a beta). We'd like to make sure we create a good impression when we go through that channel since even with all the indicators available, people will still have expectations of quality. These are mostly quality issues (reaction speed of the RLS, stability (lack of crashes), lack of bugs, etc., There are also some technical issues to making sure that all users get a good experience - distributing binaries, library data, etc. We believe it is better to concentrate on getting all these things to a good place before distributing through the marketplace.

**Comment by perlun** [comment]
> We believe it is better to concentrate on getting all these things to a good place before distributing through the marketplace.

Fair enough, I can buy into that. Let's keep the issue open until we feel that it's mature enough to go to the Marketplace.

**Comment by perlun** [comment]
Actually, it broke down for me now after updating the Rusty Code plugin. 😆 Disabling it, restarting code etc doesn't work. Code completion still works, but the squiggly markings of syntax errors, hovering symbols have broken down. Any ideas on how to debug it @nrc @jonathandturner? It says "RLS analysis: done" at the bottom status bar.

**Comment by nrc** [comment]
I'm afraid debugging the RLS is something of a dark art at the moment. If you want I can go over some things on irc next week (I'm on leave this week). In the meantime, the key thing to know is that vs code will send stderr to the 'output' console (open via the view menu, select rls from the drop down on the right).

You can then turn on debugging output, which uses the standard env logger, or you can add your own `writeln(::std:::io::stderr(), ...)` statements. You can't use `println!` since that writes to stdout.

**Comment by perlun** [comment]
It works for me again. 😃

**Comment by ctaggart** [comment]
RLS is being integrated in vscode-rust.
https://marketplace.visualstudio.com/items?itemName=kalitaalexey.vscode-rust

https://github.com/KalitaAlexey/vscode-rust/pull/56
See features in https://github.com/KalitaAlexey/vscode-rust

I'd prefer that it simply be improved. I guess was this was more of a test project not to be published. Perhaps I'm wrong.

**Comment by jonathandturner** [comment]
We haven't really made the decision on whether this will be official, yet.  There is some sense to it, as the test bed for new features it should be a pretty stable, featured experience that tracks pretty closely with the RLS.

**Comment by nrc** [comment]
Done - https://marketplace.visualstudio.com/items?itemName=rust-lang.rust
