### ISSUE TITLE
RLS could not set RUST_SRC_PATH for Racer because it could not read the Rust sysroot.

### ISSUE THREAD

**Issue by zanjs** [rust-lang-nursery/rls-vscode#167]
<img width="637" alt="wx20171002-185753 2x" src="https://user-images.githubusercontent.com/12947276/31074409-23852eda-a736-11e7-967a-fc39e4521fed.png">

**Comment by Pzixel** [comment]
Why did you close it? How to fix it?

**Comment by Andrew-Webb** [comment]
@Pzixel - I fixed this by allowing VSCode to install the nightly toolchain components for `Rust (rls)`.

**Comment by Andrew-Webb** [comment]
Indeed, the `Rust (rls)` extension lists as one of its requirements:-

"A nightly Rust toolchain (the extension will configure this for you, with permission),"

**Comment by andradei** [comment]
@Andrew-Webb How do you allow VSCode to install the nightly toolchain? I have nightly already installed and the plugin doesn't ask me to install it...

**Comment by Andrew-Webb** [comment]
@andradei - When I first used it, RLS prompted me to install the nightly toolchain components.  After I allowed it to, and restarted, the error "RLS could not set RUST_SRC_PATH for Racer because it could not read the Rust sysroot." went away.

I now see that with RLS 0.3.2 the extension no longer mentions the nightly toolchain as one of its requirements.  The requirements are:-

* Rustup
* A Rust toolchain (the extension will configure this for you, with permission),
* RLS (currently rls-preview), rust-src, and rust-analysis components (the extension will install these for you, with permission).

Maybe you need to `rustup update` to update your nightly?

**Comment by andradei** [comment]
@Andrew-Webb I ran `rustup update` a lot this last time... I have stable and nightly toolchains installed. No dice.

**Comment by KaneGreen** [comment]
@Andrew-Webb I allowed vscode to configure Rust toolchain, rls-preview, rust-src, and rust-analysis but it took me a lot of time. So, I closed vscode and I wanna configure by myself. As you said, it doesn't need the nightly toolchain any more. So, I'm using `stable-x86_64-pc-windows-msvc`. However, the extension doesn't work, either.

**Comment by prycejs** [comment]
This issue seems to have changed now that nightly toolchain is not required.

Further, the VSCode extension kept offering to install the `nightly` toolchain, which I do not want.

Using the current version of the rls VSCode exension, 0.4.5, release 2018-06-03, I had to solve this problem in early June 2018 I did the following:

1. First, edit my VS Code settings to add the following two entries in my user settings:
```
    "rust-client.channel": "stable",
    "rust-client.logToFile": true
```
The 'logToFile' part is not strictly necessary - it means that if or when `rls` fails you get a log entry you can examine to see what went wrong to help you figure out the problem.

2. Restart VS Code

3. On restart, a popup offered to install RLS  (but did not mention the `nightly` toolchain anymore. I chose `yes`.

After this, the VSCode extension appears to be working for me.

**Comment by maxdesiatov** [comment]
Seems to me that `"rust-client.channel": "stable"` should be the default now that `nightly` is no longer a requirement.
