### ISSUE TITLE
Keywords, primitives (basic syntax) in IntelliSense/Completion?

### ISSUE THREAD

**Issue by dmcneil** [rust-lang-nursery/rls-vscode#314]
Is there a way to enable IntelliSense/Word Completion for built-in keywords and primitives Rust has such as `let`, `let mut`, `i32`, `i64`, etc.? I know these are pretty basic things but as I learn and become more familiar with the language, it's helpful to have the basic language keywords in auto-completion much like the IDEA Rust plugin does.

Perhaps there is more of a syntax-related extension I am missing in the Marketplace that partners well with RLS-VSCode for this?

**Comment by nrc** [comment]
These would be implemented as snippets, rather than intellisense. I've avoided adding too many snippets to the extension (e.g., one for each keyword) since on an informal survey of users, the majority preferred having a small number of high value snippets rather than lots of them (which as you point out, might be best for beginners). I think it would be great if someone created an extension which was just a collection of lots of Rust snippets, but I'm not aware of one existing yet.

**Comment by nrc** [comment]
CLosing since I don't think we'll ever add such a thing to this extension.
