### ISSUE TITLE
Goto implementation command needs updating

### ISSUE THREAD

**Issue by dgriffen** [rust-lang-nursery/rls-vscode#368]
As of [this](https://github.com/rust-lang-nursery/rls/pull/936) in the rls repo the rls now uses the standard `textDocument/implementation` command instead of `rustDocument/implementations`. The menu item provided by this extension should be fixed to use the correct method (either via configuration or some other manner)

**Comment by Xanewok** [comment]
Just changing the command at https://github.com/rust-lang-nursery/rls-vscode/blob/master/src/extension.ts#L214 works now.

However, looking at the vscode and vscode-languageserver-node LSP client lib we're using, it should automatically populate the context menus (rather than us having to manually add the context menu item ourselves) - looking at it right now.

**Comment by Xanewok** [comment]
Hopefully https://github.com/Microsoft/vscode/pull/54317 will be merged - this will bring standard VSCode Go to Implementation to the menu and we won't have to manually register the action anymore.

Until then we should use a fallback, at least for the full nightly -> stable release cycle.
