### ISSUE TITLE
Unused warnings with test code

### ISSUE THREAD

**Issue by shanegibbs** [rust-lang-nursery/rls-vscode#83]
I am not sure if this is a config issue for the plugin or not, but I get the following warnings from the plugin and I get no warnings when compiling and testing using cargo. 

Plugin version 0.1.0

```
§ cargo -V
cargo 0.21.0-nightly (f709c35a3 2017-07-13)
§ rustc --version
rustc 1.20.0-nightly (8f1339af2 2017-07-16)
```

![screen shot 2017-07-17 at 11 18 03 am](https://user-images.githubusercontent.com/2838876/28278218-eed1fbf4-6ae1-11e7-8ba7-8f1a6bb3e32b.png)

**Comment by nrc** [comment]
cc https://github.com/rust-lang-nursery/rls/issues/252

Yeah, this is unfortunate - it is due to the way that we check test code and needs a feature added to the compiler to fix it (the design of which is a bit unclear). In the meantime you can either not check tests or suppress warnings (using configuration settings) to make this less annoying (those might need today's nightly Rust to work).
